name: CI - Payment Functions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: Remove sonar-project.properties
        run: rm -f sonar-project.properties

      - name: SonarCloud Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"estudosfiapfcg_fiap-fcg-payment-functions" \
            /o:"estudosfiapfcg" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${SONAR_TOKEN}" \
            /d:sonar.projectBaseDir="${{ github.workspace }}" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" \
            /d:sonar.coverage.exclusions="**/*Program.cs,**/*Startup.cs,**/*Migrations/**" \
            /d:sonar.exclusions="**/.github/**,**/ci/**,**/cd/**,**/build/**,**/obj/**"

      - name: Restore
        working-directory: Fiap.FCG.Payment.Functions
        run: dotnet restore

      - name: Build
        working-directory: Fiap.FCG.Payment.Functions
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage (OpenCover)
        working-directory: Fiap.FCG.Payment.Functions
        run: |
          dotnet test test/Fiap.FCG.Payment.Functions.Unit.Test/Fiap.FCG.Payment.Functions.Unit.Test.csproj \
            --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" \
            /p:CollectCoverage=true \
            /p:CoverletOutput=${{ github.workspace }}/Fiap.FCG.Payment.Functions/test/Fiap.FCG.Payment.Functions.Unit.Test/TestResults/coverage.opencover.xml \
            /p:CoverletOutputFormat=opencover

      - name: SonarCloud End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${SONAR_TOKEN}"

      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: .sonarqube/out/.sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
